--- contrib/sasc-ng/dvbloopback/module/config-dvb/Makefile
+++ contrib/sasc-ng/dvbloopback/module/config-dvb/Makefile
@@ -2,7 +2,7 @@
 
 obj-m = chkdvb.o
 
-EXTRA_CFLAGS ?= -Idrivers/media/dvb/dvb-core/ -I$(PWD)
+EXTRA_CFLAGS ?= -Idrivers/media/dvb-core/ -I$(PWD)
 
 BUILD_DIR := /lib/modules/$(shell uname -r)/build
 
