--- contrib/sasc-ng/dvbloopback/module/Makefile
+++ contrib/sasc-ng/dvbloopback/module/Makefile
@@ -4,12 +4,14 @@
 dvbloopback-objs := dvb_loopback.o dvblb_proc.o dvblb_forward.o
 
 ifdef DVB_DIR
-  EXTRA_CFLAGS = -I$(DVB_DIR) -I$(DVB_DIR)/drivers/media/dvb/dvb-core
+  EXTRA_CFLAGS = -I$(SOURCE_DIR) -I$(SOURCE_DIR)/include \
+     -I$(SOURCE_DIR)/include/uapi -I$(SOURCE_DIR)/arch/x86/include \
+     -I$(DVB_DIR)/drivers/media/dvb-core
   DVB_SRC = $(DVB_DIR)
   SYMVER = $(DVB_DIR)/../v4l/Module.symvers
   have_modver := $(wildcard $(SYMVER))
 endif
-EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/ -I$(PWD)
+EXTRA_CFLAGS += -Idrivers/media/dvb-core/ -I$(PWD)
 
 BUILD_DIR ?= /lib/modules/$(shell uname -r)/build
 
